query getLoans {
  loans {
    loanId
    classroomCode
    userId
    requesterName
    loanDate
    startTime
    endTime
    reason
    status
  }
}

query getLoansByUser($userId: ID!) {
  loansByUser(userId: $userId) {
    loanId
    classroomCode
    userId
    requesterName
    loanDate
    startTime
    endTime
    reason
    status
  }
}

mutation createLoan(
  $classroomCode: String!
  $loanDate: String!
  $startTime: String!
  $endTime: String!
  $reason: String!
) {
  createLoan(
    classroomCode: $classroomCode
    loanDate: $loanDate
    startTime: $startTime
    endTime: $endTime
    reason: $reason
  ) {
    loanId
    status
  }
}

mutation updateLoanStatus($loanId: ID!, $status: String!) {
  updateLoanStatus(loanId: $loanId, status: $status) {
    loanId
    status
  }
}
