mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      userId
      fullname
      email
      roleId
      roleName
    }
  }
}

mutation Register(
  $fullname: String!
  $email: String!
  $password: String!
  $roleName: String
  $legalId: String
) {
  register(
    fullname: $fullname
    email: $email
    password: $password
    roleName: $roleName
    legalId: $legalId
  ) {
    token
    user {
      userId
      fullname
      email
      roleId
      roleName
    }
  }
}

query getUsers {
  users {
    userId
    fullname
    email
    roleId
    roleName
  }
}

query getRoles {
  roles {
    roleId
    name
  }
}

mutation createUser(
  $fullname: String!
  $email: String!
  $password: String!
  $roleName: String!
  $legalId: String!
) {
  createUser(
    fullname: $fullname
    email: $email
    password: $password
    roleName: $roleName
    legalId: $legalId
  ) {
    userId
    fullname
    email
    roleName
  }
}

mutation updateUserRole($userId: ID!, $roleName: String!) {
  updateUserRole(userId: $userId, roleName: $roleName) {
    userId
    roleName
  }
}

mutation deleteUser($userId: ID!) {
  deleteUser(userId: $userId)
}

mutation updateProfile($userId: ID!, $fullname: String, $email: String) {
  updateProfile(userId: $userId, fullname: $fullname, email: $email) {
    userId
    fullname
    email
    roleId
    roleName
  }
}

mutation changePassword($userId: ID!, $currentPassword: String!, $newPassword: String!) {
  changePassword(userId: $userId, currentPassword: $currentPassword, newPassword: $newPassword)
}
